name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: GitHubAction/Root/Dev

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: GitHubAction/Root/Dev

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: GitHubAction/Root/Dev

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve
        working-directory: GitHubAction/Root/Dev

      - name: Save Terraform Output
        run: terraform output -json > terraform_output.json
        working-directory: GitHubAction/Root/Dev
