

name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run Terraform based on branch name
        run: |
          

          terraform init
          terraform fmt -check
          terraform plan -input=false

          terraform apply -input=false -auto-approve
          terraform output -json > terraform_output.json
